= Schnittstellen Turnierprogramme

== Einleitung

=== Änderungshistorie

*xx.xx.xxxx / Version 2.0.0*

* Hinweise zu Schnittstellen-Level 2 und JSON-Schemata
* Funktionäre/Lizenzträger (Einzelaufruf und Gesamtliste): das Jahr als
optionalen URL-Parameter zugefügt
* Funktionäre/Lizenzträger (Gesamtliste): Gesamtliste liefert auch Namen
zurück
* Wertungsrichterzettel (digital): Objekt wr ergänzt
* Ergebnis: Kürzel für Wertungsrichter, Turnierleiter, Beisitzer und
Chairpersonen

*19.05.2015 / Version 1.6.2*

* PDF-Upload: Details ergänzt
* Gesamtstartliste: globales Feld [nachmeldungen] und Feld
[startmeldungen] je Starter sind leere Arrays
* API-Responses im Anhang und bei schreibenden Zugriffen ergänzt
* Dokumentstruktur und –formatierung überarbeitet

*07.05.2015 / Version 1.6.1*

* Zusatzinfo Ergebnisupload Verwarnungs/Disqualifikations-Flag
* Schlüsselverzeichnis WR-Lizenzen: WR-B getrennt in WR-B-Std und
WR-B-Lat
* Angabe, welche Felder in der Gesamtstartliste einer Wettbewerbsart
NULL sind
* Ergebnisupload und digitale WR-Zettel: Vorgabe zur Verfahrensweise,
wenn Tänze in einer Runde nicht getanzt wurden
* Digitaler WR-Zettel: Datentyp für Einzelkreuz ist gemischt (Float für
Wertung oder „L“ für Lift); Vorgabe zur Verfahrensweise, wenn die
Wertungsdaten nicht vollständig digital vorliegen; Feldname für
Unterschrift ergänzt
* Skatingtabelle: Klarstellung zur Übermittlung, falls das Skatingsystem
nicht angewandt wurde

*25.03.2015 / Version 1.6*

* Ergebnis-Interface ergänzt um Sterne-Info bei Startern

*12.03.2015 / Version 1.5*

* Startlistendownload: Flag Nachmeldeerlaubnis nun Array; Klarstellung
zu globalen Parametern in der Gesamtstarterliste je Wettbewerbsart
* Ranglistenschnittstelle: Beispielaufruf ohne Stichtag ergänzt
* Aufstiegstabelle: Feld Zielklasse ergänzt
* Neue Schnittstelle: Ausgefallenes (einzelnes) Turnier
* Leerzeichen und Punkte aus Konstanten im Schlüsselverzeichnis entfernt
(LTVs, Startgruppen, Startklassen, RL-IDs)

*03.03.2015 / Version 1.4.1*

* Feldnamen JSON ergänzt (keine inhaltlichen Änderungen)
* Abkürzungen für Tänze (gem. TSO) und Wettbewerbsarten korrigiert
* Schnittstelle Aufstiegstabelle ergänzt (fehlte in dieser Version des
Dokumentes)

*13.02.2015 / Version 1.4*

* Alle GET/POST-Aufrufe auf vereinbarten Modus reduziert
* Einzelstarteraufruf erweitert
* Ergebnisupload um Clubdaten bereinigt

*06.02.2015 / Version 1.3*

* Veranstaltungsdownload: Flag entfernt
* Startlistendownload: Startbuchdaten sind ein Array über alle
betroffenen Turnierarten
* Startlistendownload: Startsperre-Flag eingefügt
* Ranglistendownload um ein Feld erweitert
* Ergebnisupload: Platz-Felder erweitert
* Abkürzungen hinten angefügt
* Fehlercodes vergeben

*28.01.2015 / Version 1.2*

* Ergebnisupload, Punkt Startbuch->Ziel-Startklasse überarbeitet
* Prüfsummenmechanismus ergänzt

*21.01.2015 / Version 1.1*

* Ergebnisupload überarbeitet
* Starterdownload überarbeitet

*9.12.2014 / Version 1.0*

* Turnierprogramme/Startlisten: Flag für Verwarnung Schrittbegrenzung
ist eine Eigenschaft der Turnierart; in Startbuchdaten je Turnierart
verschoben und mit Laufzettel-Flag in einem Objekt zusammengefasst
* Startlisten: Nationalität bei einzelner Person hinzugefügt
* Startlisten: Nachmeldung-Erlaubt-Flag hinzugefügt
* Ergebnisupload: Ergänzung für Digitale Wertungsdaten und Hinweise zu
Upload Zwischenergebnisse
* Interface für PDF-WR-Zettel-Upload
* Flag im Veranstaltungsdatensatz für „Trotz kombiniertes Turnier nur
Gesamtplätze hochladen“
* Dokumente gesplittet und Interfacereihenfolge überarbeitet
* Anmerkungen zum Datenmodell erweitert
* Veranstaltungsdaten: Veranstalter und Ausrichter der
Veranstaltungsebene hinzugefügt, Bemerkungstextfelder auf
Veranstaltungs- und Turnierebene hinzugefügt, Rückgabe der Liste bei
Verbandsanfragen: alle Turniere im Kalender, Wertungsrichter und
Funktionäre auf beiden Ebenen hinzugefügt
* Funktionärsdaten: WDSF-MIN und alte Lizenznummer hinzugefügt
* Ergebnis-Interface überarbeitet (Wertungstyp rundenweise hinzugefügt.
Wertungen, Wertungstabellen und Digitale Wertungen überarbeitet)
* Digitale Wertungsrichterzettel JSON überarbeitet und Felder aus dem
eigentlichen Ergebnisdatensatz rausgenommen. Ist getrennt zu übertragen

=== Datenmodell

* Veranstalter und Veranstalter-ID +
ist i.d.R. ein Verein, es kann aber auch ein LTV sein oder auch der
DTV. Es kann auch eine Veranstaltergemeinschaft sein (z.B. eine Gruppe
von Vereinen), für die im Datenmodell in einer geeigneten Entität ein
Eintrag vorhanden sein muss +
Jede Veranstaltung ist eindeutig einem Veranstalter zugeordnet.
* Ausrichter und Ausrichter-ID +
ist der Verein oder der Verband (LTV bzw. DTV), der das Turnier
durchführt. +
Jedes Turnier ist eindeutig einem Ausrichter zugeordnet.
* Veranstaltung +
sind alle Turniere, die ein Veranstalter für ein (auch verlängertes)
Wochenende angemeldet hat. Beispiele: GOC, Blaues Band der Spree, Hessen
tanzt, danceComp, Tanzen im Dreiländereck (Aachen). Es ist nötig,
Veranstaltungen als eigenständige Entität mit eigener ID zu erstellen.
* Starter-ID (übergreifend über alle Tänzer der tänzerischen
Einheit/Paar/Gruppe etc.) +
wird innerhalb der ESV-Datenbank für die Verbindung mehrerer Tänzer zu
einem Starter vergeben. Im Live-Modus kann mit der Starter-ID der
Aufstiegsdaten-Status eines einzelnen Starters abgefragt werden, was
aber nur dann möglich sein soll, wenn der Starter für mindestens eines
der Turniere der Veranstaltung in der Startliste erscheint und damit die
Starter-ID dem Turnierprogramm bekannt ist.
* Akademische Titel +
In der bisherigen DTV-Datenbank ist kein Feld für den Titel „Dr.“
vorhanden. Ein Titel wird bisher in das Feld des Vornamens eingetragen
(z.B. „Thomas Dr.“). In der ESV-Datenbank sollte ein separates Feld
dafür vorgesehen werden. Über die Stammdatenerfassung der Personen kann
jeder Beteiligte selbst entscheiden, ob er den Titel im Sportbetrieb
führen will.
* User +
Über den User ist im ESV-System geregelt, welche Veranstaltungen er
überhaupt lesen und schreiben darf (z.B. Verein, LTV, etc.)
* Kennschlüssel +
Jedes zertifizierte Turnierprogramm/jede externe Software soll einen
eindeutigen Kennschlüssel erhalten, woraus ersichtlich ist, dass es sich
um eine bestimmte zertifizierte/zugelassene Software handelt. Für jede
Einzelschnittstelle muss hinterlegt werden, ob mit dem jeweiligen
Schlüssel lesend, schreibend oder gar nicht auf die jeweils angefragte
Schnittstelle zugegriffen werden kann.
* Optionale Datenfelder +
Diese Felder sind grundsätzlich immer im Datensatz vorhanden, ggf.
werden sie mit NULL gefüllt.
* Staaten +
in 3-Buchstaben-Olympiccode, bei den Staaten ohne solchen: ISO-3-Code
* User und Passwort +
Als User und Passwort werden die Vereinsportal-Zugangsdaten verwendet

=== Ablauf

* Lesen der Startlisten +
Das Turnierprogramm wird zuerst die Liste der Veranstaltungsdaten (des
Users) lesen. In einem zweiten Schritt wird es dann die Informationen zu
den einzelnen Veranstaltungen lesen und in einem dritten Schritt die
Startlisten der einzelnen Veranstaltungen mit den einzelnen Turnieren.
Sobald eine Veranstaltung in der Liste der Veranstaltungen vorliegt,
können die Veranstaltungsdaten und die Startlisten beliebig oft gelesen
werden. +
Wird ein Turnierprogramm im Live-Modus betrieben, können die Daten der
Einzelstarter ebenfalls beliebig oft abgefragt werden.

=== Kodierung

* Alle Datensätze werden als JSON-Konstrukt übertragen (Feldnamen in
eckigen Klammern)
* Die JSON-Kodierung erfolgt streng nach Vorgaben aus RFC 4627
** Strings können alle Unicode-Zeichen enthalten
*** Anführungszeichen, Backslash und Steuerzeichen (U+0000 bis U+001F)
müssen escaped werden
*** Die Unicode-Zeichen von U+0000 bis U+FFFF (Basic Multilingual Plane,
BMP) können, müssen jedoch nicht als 6 Zeichen lange hexadezimale
Unicode-Sequenz dargestellt werden (z.B. \u00fc). Alternativ Zeichen
direkt in UTF-8.
*** Die Unicode-Zeichen außerhalb des BMP werden als surrogate pair
dargestellt.
* Alle JSON-Schnittstellen sollen transparente HTTP-Komprimierung
unterstützten (gzip, deflate via Accept-Encoding und Content-Encoding)

===  Schnittstellen-Level

* Mit Version 2.0.0 wird für alle beschreibbaren Endpunkte ein
Schnittstellen-Level eingeführt. Da es sich nur um abwärtskompatible
Änderungen der Struktur handelt, die jedoch hohe inhaltliche Relevanz
haben, gibt es keine neue Endpunkt-URL.
* Für alle Endpunkte gibt es ab Version 2.0.0 ein JSON-Schema
(json-schema.org, draft-06), das eine grundsätzliche Validierung der
JSON-Daten ermöglicht.
* Sofern es sich um beschreibbare Endpunkte handelt, muss der durch das
Turnierprogramm verwendete Schnittstellen-Level durch die Angabe der URI
des verwendeten JSON-Schemas (korrespondierend mit dem
Schnittstellen-Level) über die Eigenschaft $schema des JSON-Dokuments
erfolgen, sofern ein Schnittstellen-Level > 1 verwendet wird.
* Die Schema-Dateien können über die jeweilige Schema-URI bezogen
werden.
* Unter https://github.com/tanzsport/esv-json-schema kann ein
GIT-Repository der Schema-Dateien inkl. Kompatibilitäts-Tester
(basierend auf NodeJS) bezogen werden.
* Die für die jeweiligen Endpunkte gültigen Level-Schemas sind der
folgenden Tabelle zu entnehmen.

[cols=",,",options="header",]
|===
|*Endpunkt* |*Level* |*Schema-URI*
|Ergebnisse |2
|http://schema.tanzsport.de/json/esv/v1/ergebnis-level2.json

|WR-Zettel (digital) |2
|http://schema.tanzsport.de/json/esv/v1/wrzetteldigi-level2.json
|===

== Schnittstellen

=== Veranstaltungsdaten (lesend)

Dieses Interface ist vorrangig für Turnierprogramme gedacht. Das
Rückgabeformat „Veranstaltung“ könnte aber auch für den
Tanzsport.de-Turnierkalender Verwendung finden. Deshalb werden mehr
Werte zurückgegeben als für die Turnierprogramme benötigt.

==== Liste

===== Aufruf

* HTTP-Verb: GET
* HTTP Header: User + Passwort (Basic Authentication)
* HTTP Header: User-Agent (Software inkl. Version + Kennschlüssel)

[source]
----
GET /api/v1/veranstaltungen HTTP/1.1
Authorization: Basic dXNlcjpwYXNzd29yZA==
User-Agent: Software/1.0; Token=abcdefghijklmnopqrstuvwxyz
----

===== Rückgabe

* Array Veranstaltungen (alle Veranstaltungen in den folgenden 2 Monaten
bei Vereinsanfrage/alle bei Landesanfrage, zu denen der User
Berechtigung hat)
** Veranstaltungs-ID [id]
** Datum Von [datumVon]
** Datum Bis [datumBis]
** Ort [ort]
** Titel (optional) [titel]

==== Einzelaufruf

===== Aufruf

* HTTP-Verb: GET
* HTTP Header: User + Passwort (Basic Authentication)
* HTTP Header: User-Agent (Software inkl. Version + Kennschlüssel)
* URL-Parameter: Veranstaltungs-ID

[source]
----
GET /api/v1/turniere/{veranstaltungsId} HTTP/1.1
Authorization: Basic dXNlcjpwYXNzd29yZA==
User-Agent: Software/1.0; Token=abcdefghijklmnopqrstuvwxyz
----

===== Rückgabe

* Veranstaltung
** Veranstaltungs-ID [id]
** Datum Von [datumVon]
** Datum Bis [datumBis]
** Turnierstätte [turnierstaette]
*** Name [name]
*** Anschrift (Straße + Nr) [anschrift]
*** PLZ [plz]
*** Ort [ort]
** Veranstalter [veranstalter]
*** ID [id]
*** Name [name]
*** LTV (optional) [ltv]
**** ID [id]
**** Name [name]
** Ausrichter [ausrichter]
*** ID [id]
*** Name [name]
*** LTV (optional) [ltv]
**** ID [id]
**** Name [name]
*** Kontakt Telefon [kontaktTelefon]
*** Kontakt E-Mail [kontaktEmail]
** Titel (optional) [titel]
** Bemerkungen (Freitext, optional) [bemerkungen]
** Array Wertungsrichter (optional) [wertungsrichter]
*** Inhalte wie bei Einzelaufruf Funktionäre (siehe unten)
** Array Funktionäre (TL, BS, CHM, optional) [funktionaere]
*** Inhalte wie bei Einzelaufruf Funktionäre (siehe unten)
* Array Flächen [flaechen]
** Flächen-Bezeichnung (eindeutig innerh. der Veranstaltung) [id]
** Typ (Text: z.B. Parkett, Kunststoff, Stein) [typ]
** Länge (in Metern; Kommawert z.B. 10,5; Länge ≥ Breite) [laenge]
** Breite (in Metern; Kommawert) [breite]
* Array Turniere [turniere]
** Turnier-ID [id]
** Datum Von [datumVon]
** Datum Bis [datumBis]
** Startzeit Plan (Zeit, die im Tanzspiegel veröffentlicht wurde)
[startzeitPlan]
** Startzeit Plan Korrigiert (kann, sofern vom Ausrichter verändert auch
im Terminkalender als veränderte Startzeit kenntlich dargestellt werden)
[startzeitPlanKorrigiert]
** Titel (optional) [titel]
** Veranstalter [veranstalter]
*** ID [id]
*** Name [name]
*** LTV (optional) [ltv]
**** ID [id]
**** Name [name]
** Ausrichter [ausrichter]
*** ID [id]
*** Name [name]
*** LTV (optional) [ltv]
**** ID [id]
**** Name [name]
** Flächen-ID [flaechenID]
** Wettbewerbsart (z.B. Einzel, Formation, Solo, Duo,…) [wettbewerbsart]
** Turnierform [turnierform]
** Startgruppe [startgruppe]
** Startklasse oder Startliga [startklasseLiga]
** Turnierart [turnierart]
** Zulassung (grenzt die zugelassenen Paare ein, z.B. DTV oder auf einen
oder mehrere LTV;) [zulassung]
*** Array; mögliche Werte: WDSF, EU, DTV + LTVs
** Wanderpokal: true/false [wanderpokal]
** Turnierrang (numerisch) [turnierrang]
** Flag Aufstiegsturnier (Vergabe von Aufstiegspunkten und
–platzierungen ja/nein) [aufstiegsturnier]
** Ranglisten-ID (optional, bei Ranglistenturnieren und ggf. bei DM)
[ranglistenId]
** WDSF-Turnier-ID (optional) [wdsfTurnierId]
** Startgebühr in EUR (optional, Zahlwert oder Freitext) [startgebuehr]
** Bemerkungen (Freitext optional) [bemerkungen]
** Array Wertungsrichter (optional) [wertungsrichter]
*** Personen-ID
** Turnierleiter Personen-ID (optional) [turnierleiter]
** Beisitzer Personen-ID (optional) [beisitzer]
** Chairman Personen-ID (optional) [chairman]

=== Startlisten (lesend)

Startlisten können für eine spezifische Veranstaltung oder als
Gesamtstartliste für eine Wettbewerbsart zur Offline-Verwendung
heruntergeladen werden. Die Gesamtstartliste einer enthält aus
Datenschutzgründen keine Namen der Personen (Feldwerte [titel],
[vorname], [nachname], [geschlecht] sind NULL).

==== Veranstaltung

===== Aufruf

* HTTP-Verb: GET
* HTTP Header: User + Passwort (Basic Authentication)
* HTTP Header: User-Agent (Software inkl. Version + Kennschlüssel)
* URL-Parameter: Veranstaltungs-ID (ggf. optional)

[source]
----
GET /api/v1/startliste/veranstaltung/{veranstaltungsId} HTTP/1.1
Authorization: Basic dXNlcjpwYXNzd29yZA==
User-Agent: Software/1.0; Token=abcdefghijklmnopqrstuvwxyz
----

==== Rückgabe

*Global*:

* Gültigkeits-Flag für Meldestand (0 = Turniermeldungen noch nicht
gestartet, 1 = Meldestand noch nicht final, 2 = Meldestand final)
[status]; NULL in Gesamt-Starterliste
* Array Nachmeldungen möglich: Liste der Turnier-IDs mit
Nachmeldeerlaubnis [nachmeldungen]; leer in Gesamt-Starterliste

Erläuterung: +
Turnierprogramme können die Startdaten ab dem Start der Turniermeldungen
herunterladen (z.Z. der 21. des Vorvormonats). Der finale Meldestand
inkl. der aktuellen Aufstiegsdaten kann frühestens am Tag vor dem
Turnier geladen werden – er wird im Gültigkeits-Flag als solcher
gekennzeichnet.

*Starterweise [starter]*:

* Starter-ID (übergreifende ID für tänzerische Einheit) [id]
* Team (optional, nur bei Formations-, Small-Group- und
Mannschaftswettbewerben) [team]
** Team-Name (sofern vorhanden, z.B. bei Gruppen+Formationen) [name]
** Team-Kapitän (sofern vorhanden, z.B. bei Gruppen+Formationen)
[kapitaen]
** Team-Trainer (sofern vorhanden, z.B. bei Gruppen+Formationen)
[trainer]
* Personen (Array, enthält bei Teamwettbewerben alle Tänzer inkl.
Ersatztänzer) [personen]:
** Personen-ID (DTV-Nummer) [id]
** Titel (nur bei Einzelaufruf Veranstaltung, sonst NULL) [titel]
** Vorname (nur bei Einzelaufruf Veranstaltung, sonst NULL) [vorname]
** Nachname (nur bei Einzelaufruf Veranstaltung, sonst NULL) [nachname]
** Geschlecht (nur bei Einzelaufruf Veranstaltung, sonst NULL)
[geschlecht]
** WDSF-MIN (optional, sofern vorhanden) [wdsfMin]
** Nationalität (3-Buchst.-Code) [nationalitaet]
* Club (bei deutschen Paaren Pflicht, sonst optional) [club]
** Club-ID [id]
** Club-Name [name]
** LTV (bei deutschen Paaren Pflicht, sonst optional) [ltv]
*** LTV-ID [id]
*** LTV-Name [name]
* Staat (Staat, für den der Starter an den Start geht) [staat]
* Meldungen (Array, leer bei Aufruf der Gesamt-Starterliste für eine
Wettbewerbsart) [meldungen]
** Turnier-ID (nur die IDs der Turniere der aufgerufenen Veranstaltung)
[turnierId]
** Flag Meldung (Meldung = true, Abmeldung = false) [meldung]
** Datum der Meldebestätigung (durch Verein) [bestaetigt]
** Startnummer (optional – wird erst später für Ligaturniere relevant
sein wie JMD und Formation) [startNr]
** Flag Startsperre (true/false) [startsperre]
* Array Startbuch turnierartweise (optional, nur Einzelwettbewerbe
St/Lat und JMD, nur Turnierarten für die ein elektronisches Startbuch
vorliegt, in der Übergangszeit ggf. komplett leer) [startbuch]
** Turnierart [turnierart]
** Startgruppe [startgruppe]
** Ist-Startliga (optional, nur Formationswettbewerbe St/Lat und JMD)
[startliga]
** Ist-Startklasse (z.B. BSW, D, C,B,A,S,PD) (optional, nur bei
Einzelwettbewerben St/Lat und JMD) [startklasse]
** Ziel-Startklasse (C,B,…, NULL für BSW/S/PD/ausländische-Paare/alle
Doppelstartpaare, die nicht weiter aufsteigen können, d.h. „kein
Aufstieg möglich bei diesem Turnier für dieses Paar“; optional, nur bei
Einzelwettbewerben St/Lat, ggf. später Einzelwettbewerbe JMD)
[naechsteStartklasse]
** Punkte (optional, nur bei Einzelwettbewerben St/Lat, ggf. später
Einzelwettbewerbe JMD) [punkte]
*** Ist [ist]
*** Ziel [ziel]
** Platzierungen (optional, nur bei Einzelwettbewerben St/Lat, ggf.
später Einzelwettbewerbe JMD) [platzierungen]
*** Ist [ist]
*** Ziel [ziel]
** Regeln (optional, nur bei Einzelwettbewerben St/Lat, ggf. später
Einzelwettbewerbe JMD) [regeln]
*** Mindestpunkte [minPunkte]
*** Platzierung bis Platz (einschließlich) [platzierungBis]
** Flags [flags]
*** Laufzetteldruck da Aufstiegschance am Wochenende (optional, nur bei
Einzelwettbewerben St/Lat, ggf. später Einzelwettbewerbe JMD)
[laufzettel]
*** Verwarnt wg. Figurenbegrenzung (nur Einzelwettbewerbe St/Lat)
[verwarnungSchrittbegrenzung]

==== Wettbewerbsart

===== Aufruf

* HTTP-Verb: GET
* HTTP Header: User + Passwort (Basic Authentication)
* HTTP Header: User-Agent (Software inkl. Version + Kennschlüssel)
* URL-Parameter: Wettbewerbsart

[source]
----
GET /api/v1/startliste/wettbewerbsart/{wettbewerbsart} HTTP/1.1
Authorization: Basic dXNlcjpwYXNzd29yZA==
User-Agent: Software/1.0; Token=abcdefghijklmnopqrstuvwxyz
----

===== Rückgabe

Wie Startliste für Veranstaltung. Die Felder [titel], [vorname],
[nachname], [geschlecht] sind NULL, das Feld [startmeldungen] ist ein
leeres Array. Die globalen Felder [status] und [nachmeldungen] sind NULL
bzw. leer.

=== Ranglisten (lesend)

==== Aufruf

* HTTP-Verb: GET
* HTTP Header: User + Passwort (Basic Authentication)
* HTTP Header: User-Agent (Software inkl. Version + Kennschlüssel)
* URL-Parameter: RL-ID (Mehrfachnennung mit versch. IDs möglich)
* URL-Parameter: Stichtag (ttmmjjjj, optional, ohne Angabe letzter
Stand)

*Ohne Stichtag*:
[source]
----
GET /api/v1/ranglisten/{ranglistenId1},{ranglistenId2},... HTTP/1.1
Authorization: Basic dXNlcjpwYXNzd29yZA==
User-Agent: Software/1.0; Token=abcdefghijklmnopqrstuvwxyz
----

*Mit Stichtag*:
[source]
----
GET /api/v1/ranglisten/{stichtag}/{ranglistenId1},{ranglistenId2},... HTTP/1.1
Authorization: Basic dXNlcjpwYXNzd29yZA==
User-Agent: Software/1.0; Token=abcdefghijklmnopqrstuvwxyz
----

==== Rückgabe

* Global-je-RL
** RL-ID [id]
** Stand (Datum der letzten Änderung) [stand]
* Array Starter [starter]:
** Starter-ID [id]
** Rang [rang]
*** Rangliste [rl]
*** Platzierung der vorhergehenden DM [dm]
** Array über alle Personen: (nicht bei Gruppen/Formationen, bei Paaren:
Herr-ID, Dame-ID,…) [personen]
*** Personen-ID [id]
*** Titel [titel]
*** Vorname [vorname]
*** Nachname [nachname]
** Club [club]
*** ID [id]
*** Name [name]
*** LTV [ltv]
**** ID [id]
**** Name [name]
** RL-Punkte [punkte]
** Anz. teilgenommene Turniere in der Saison (evtl. verwendbar für die
DM-Warnung in Std/Lat) [anzahlTurniere]

=== Funktionäre/Lizenzträger (lesend)

Lizenzträger können im Einzelabruf oder als Gesamtliste geladen werden.
Die Gesamtliste muss im Turnierprogramm nach sieben Tagen gelöscht
werden. Danach muss sie ggf. erneut heruntergeladen werden.

==== Einzelaufruf

===== Aufruf

* HTTP-Verb: GET
* HTTP Header: User + Passwort (Basic Authentication)
* HTTP Header: User-Agent (Software inkl. Version + Kennschlüssel)
* URL-Parameter: Personen-ID
* URL-Parameter: Jahr (JJJJ, optional, Standard ist das aktuelle Jahr)

[source]
----
GET /api/v1/funktionaer/{personenId}/{jahr} HTTP/1.1
Authorization: Basic dXNlcjpwYXNzd29yZA==
User-Agent: Software/1.0; Token=abcdefghijklmnopqrstuvwxyz
----

===== Rückgabe

* Personen-ID [id]
* WDSF-MIN (optional, sofern verfügbar) [wdsfMin]
* alte Lizenznummer (optional) [lizenzNr]
* Titel [titel]
* Vorname [vorname]
* Nachname [nachame]
* Club [club]
** ID [id]
** Name [name]
** LTV [ltv]
*** ID [id]
*** Name [name]
* Staat [staat]
* Array Lizenzen [lizenzen]
** Lizenz-IDs (Auflistung aller gültigen Funktionärs-Lizenzen)

==== Gesamtliste

===== Aufruf

* HTTP-Verb: GET
* HTTP Header: User + Passwort (Basic Authentication)
* HTTP Header: User-Agent (Software inkl. Version + Kennschlüssel)
* URL-Parameter: Jahr (JJJJ, optional, Standard ist das aktuelle Jahr)

[source]
----
GET /api/v1/funktionaere/{jahr} HTTP/1.1
Authorization: Basic dXNlcjpwYXNzd29yZA==
User-Agent: Software/1.0; Token=abcdefghijklmnopqrstuvwxyz
----

===== Rückgabe

* Array (Elemente wie Einzelaufruf)

=== Aufstiegstabellen (lesend)

Z.Zt. nur für Wettbewerbsart Einzel

Existiert kein Eintrag in der Tabelle (Array Kriterien), ist kein
weiterer Aufstieg möglich. +
Die Tabelle enthält auch Felder für die Ist-Klasse BSW, für die
technisch der Aufstieg ermittelt werden muss, der jedoch erst nach
Umwandlung in ein vollwertiges Startbuch vollzogen werden kann.

==== Aufruf

* HTTP-Verb: GET
* HTTP Header: User + Passwort (Basic Authentication)
* HTTP Header: User-Agent (Software inkl. Version + Kennschlüssel)

[source]
----
GET /api/v1/aufstiegstabelle/{wettbewerbsart}/{jahr} HTTP/1.1
Authorization: Basic dXNlcjpwYXNzd29yZA==
User-Agent: Software/1.0; Token=abcdefghijklmnopqrstuvwxyz
----

==== Rückgabe

* Array
** Landesverbände (Array, Landesverbände, für die die Tabelle gültig
ist, z.Zt. alle) [ltv]
** Mindest-Punkte (Mindest-Punkte, die zum Erreichen einer Platzierung
erforderlich sind) [minPunkte]
** Tabellen (Array) [tabellen]
*** Startgruppen (Array) [startgruppen]
*** Turnierart [turnierart]
*** Kriterien (Array, aufsteigend sortiert nach Klasse) [kriterien]
**** Klasse (Ist-Klasse des Paares) [klasse]
**** Ziel-Klasse des Aufstiegs [zielklasse]. Bei Ist-Klasse, die keinen
Aufstieg ermöglichen wird NULL zurückgeliefert (z.B. BSW)
**** Punkte (erforderliche Punkte für Aufstieg) [punkte]
**** Plätze (erforderliche Plätze für Aufstieg) [plaetze]
**** Platzierung Bis Platz [bisPlatz]
**** Doppelstart: true/false, kennzeichnet Aufstiege in Startklassen,
die nur im Doppelstart genutzt werden können [doppelstart]
**** Doppelstart: true/false, kennzeichnet Aufstiege in Startklassen,
die nur im Doppelstart genutzt werden können [doppelstart]

=== Ergebnisse (schreibend)

Die Ergebnisse eines Turniers können mehrfach hochgeladen werden, z.B.
im Live-Modus nach jeder Runde. Dabei können sich auch die Inhalte des
übergreifenden Berichtes verändern.

Erst nach Turnierende muss/darf die Prüfsumme enthalten sein. Dies ist
für das ESV-System das Signal, das die Daten komplett sind (Turnier
beendet). Danach können die Ergebnisse noch weitere 4 Stunden für
Korrekturen erneut hochgeladen werden. Nach 4 Stunden lässt das
ESV-System ein Hochladen nicht mehr zu.

Das Hochladen von Zwischenergebnissen (auch nur der reinen Startliste)
ist möglich. Solange das Turnier noch läuft sind Daten wie: Endzeit,
Ergebnis und Wertung (für noch nicht ausgeschiedene Starter) optional
und Rundenablauf nur teilvollständig. Das Starter-Array muss trotzdem
bei jedem Upload komplett (alle Starter inkl. abwesende) hochgeladen
werden. Jeder Upload überschreibt immer den vorherigen komplett.

Die Prüfsumme besteht aus den ersten 6 Stellen des SHA-1-Hashs des
JSON-Datenstreams.

==== Aufruf

* HTTP-Verb: POST
* HTTP Header: User + Passwort (Basic Authentication)
* HTTP Header: User-Agent (Software inkl. Version + Kennschlüssel)
* HTTP Header: Prüfsumme (optional)
* URL-Parameter: Turnier-ID

[source]
----
POST /api/v1/ergebnis/{turnierId} HTTP/1.1
Authorization: Basic dXNlcjpwYXNzd29yZA==
User-Agent: Software/1.0; Token=abcdefghijklmnopqrstuvwxyz
X-DTV-Pruefsumme: ff621b
----

==== Inhalt

*Übergreifend Bericht*:

* URI des verwendetes JSON-Schemas [$schema] (verpflichtend ab
Schnittstellen-Level 2)
* Tänze (Array, max. 10 Tänze) [taenze]
** gültige Werte: LW, TG, WW, SF, QU, SB, CC, RB, PD, JV, STD, LAT, JMD,
DF, SA,..)
* WR (Array, WR des Turniers) [wr]
** Buchstaben-Kürzel [kuerzel] (verpflichtend ab Schnittstellen-Level 2)
*** muss eindeutig für das Turnier sein
*** max. drei alphanumerische Zeichen
** Personen-ID (für DTV-WR Pflicht, für Ersatz-WR optional, für
Ausländer NULL) [id]
** Vorname [vorname]
** Nachname [nachname]
** Club [club]
*** Club-Name (optional für Ausländer) [name]
*** LTV-Name (für Ausländer NULL) [ltv]
** Staat [staat]
* Turnierleiter (Array, min. 1 Element) [tl]
** Analog WR-Einzelement (ID Pflicht, Ausnahmen auf Veranstaltungsebene
konfiguriert)
* Beisitzer (Array, min. 1 Element) [bs]
** Analog WR-Einzelement (ID Pflicht, Ausnahmen auf Veranstaltungsebene
konfiguriert)
* Chairman (optional) (Array) [ch]
** Analog WR-Einzelement
* Vorkommnisse (optional) [vorkommnisse]
* Beginnzeit (ISO8601) [beginn]
* Endzeit (ISO8601) [ende]
* Array Rundenablauf (NULL für Upload von nur-Startlisten) [ablauf]
** Schlüsselwerte: 1,R,2,3,4,5,6,7,8,9,F +
(Redance=R, bei 1.VR=1A, bei 2.VR=1B, bei Formations A-Finale=FA, bei
B-Finale=FB) [runde]
** Wertungstyp +
(Kreuze{0..1}=K, Mannschaftspunkte{1..1,5..2..2,5..3}=M,
Finalplätze{1..x}=P, FormationswertungKreuze=FK,
FormationswertungPlätze=FP, JMD-WertungenKreuze=JK,
JMD-WertungenPlätze=JP, JudgingSystem2.x=JS) [typ]
* kombiniert mit Turnier-ID (optional) [kombiniertMit]
* Zuschauerzahl [zuschauer]

FK, FP, JK und JP Wertungen sind im normalen Ergebnisarray nur wie
Kreuzsummen und Finalwertungen enthalten. Im Digitalen-Wertungs-Array
sind auch die Punktewertungen als Punkte in den verschiedenen „Tänzen“
abgelegt.

*Zeilenweise Starter [starter]*:

* Starter-ID (Pflicht bei DTV- und Grenzverkehrs-Paaren, bei WDSF-Paaren
optional) [id]
* Startnummer [startNr]
* Personen (Array, enthält bei Teamwettbewerben alle Starter, die
tatsächlich getanzt haben)
** Personen-ID (Pflicht bei DTV- und Grenzverkehrs-Paaren, bei
WDSF-Paaren optional) [id]
** Vorname [vorname]
** Nachname [nachname]
** WDSF-MIN (optional, sofern vorliegend; bei WDSF-Paaren Pflicht) [wdsfMin]
* Staat [staat]
* Status (teilgenommen = 1, fehlt entschuldigt = 2, fehlt unentschuldigt
= 3) [status]
* Meldungstyp (regulär = 1, Nachmeldung = 2, Nachmeldung, Sieger = 3,
Nachmeldung, Aufsteiger = 4) [meldungsTyp]
* Anzahl Sterne (gesetzte Paare) [sterne]
* Ergebnis (NULL bei Status 2 oder 3 oder beim Upload von
nur-Startliste) [ergebnis]
** Platz-Gesamtergebnis Von [platzGesamtVon]
** Platz-Gesamtergebnis Bis [platzGesamtBis]
** Platz-Eigenes-Turnier Von (z.B. nach Anhang 5, NULL wenn nicht
benötigt) [platzTurnierVon]
** Platz-Eigenes-Turnier Bis (z.B. nach Anhang 5, NULL wenn nicht
benötigt) [platzTurnierBis]
** Punkte [punkte]
** Platzierungen gesamt (zur Überprüfung in der DB, Adminalarm bei
Abweichung) [platzierungenGesamt]
** Punkte gesamt (zur Überprüfung in der DB, Adminalarm bei Abweichung)
[punkteGesamt]
** Aufstieg (0 = nein, 1 = ja, 2 = ja, durch Beschluss) [aufstieg]
** Flag Laufzettel (Starter hat manuell bearbeitete Aufstiegdaten)
[laufzettel]
** Flag Verwarnung/Disqualifikation (0 = keine, 1 = Verwarnt
Schrittbegrenzung, 2 = Disqualifiziert Schrittbegrenzung, 3 =
gewöhnliche Disqualifikation) [vd] +
Das Verwarnungsflag darf nur >0 gesetzt werden, wenn die Verwarnung oder
Disqualifikation innerhalb dieses Turnieres erfolgt ist. Dabei ist zu
beachten, dass es für Paare möglich ist, innerhalb eines Turnieres in
einer Runde erst verwarnt und in einer späteren Runde disqualifiziert zu
werden (in diesem Fall wird vd=2 übertragen).
* Wertung (Array mit N = Anzahl Runden Elementen; nicht getanzte Runden
werden als NULL übertragen, Runden nach Ausscheiden werden gar nicht
übertragen; werden Tänze in der jeweiligen Runde nicht getanzt, ist das
jeweilige Wertungselement mit NULL anzugeben) [wertung]
** Vorrundenwertung (nur Kreuz+Mannschaftspunkt-Wertungen)
*** Array WR
**** Array Tänze+1
***** Tänze 1-x: Float für Wertung (Einzelkreuze, sonst NULL, nicht
getanzte Tänze der Runde ebenfalls NULL)
***** Tänze+1: Float Summe +
*** Summe Wertungen über alle Tänze und alle WR
** JudgingSystem2.x: Summe Float
** Endrundenwertung (nur Final-Platz-Wertungen, bei Mannschaft wird
Struktur der Vorrundenwertung verwendet)
*** Array Tänze
**** Array WR+2
***** WR1-x: Non-signed Byte für Wertung
***** WR+1: Platzziffer
***** WR+2: Platzziffer Summe

*Einmal*:

* Array Endrundentabelle (optional, nur bei Plätzewertungen P, FP, JP,
Reihenfolge aus Rundenablauf, nur bei B/A-Finals relevant, vor
Turnierende NULL) [endrundentabellen]
** Array Tänze
*** Array über Endrundenstarter (Zeilen im heute gedruckten Dokument)
**** Array über Plätze (Spalten im heute gedruckten Dokument)
***** „Tabellenzelle“ (solange in Ausrechnung benötigt; NULL wenn
Ausrechnung in früherer Spalte beendet)
****** Anzahl [anzahl]
****** Summe (optional, sonst NULL) [summe]
* Array Skatingtabelle (Reihenfolge aus Rundenablauf, nur bei B/A-Finals
relevant, vor Turnierende leeres Array; sofern kein Skating in der Runde
angewandt ist das jeweilige Element NULL) [skatingtabellen]
** Skating Regel 10 [regel10]
*** Array über Endrundenstarter
**** Array über Plätze
***** „Tabellenzelle“ (wenn in Ausrechnung benötigt, sonst NULL)
****** Anzahl [anzahl]
****** Summe (optional, sonst NULL) [summe]
**** Platz (sofern in Regel 10 bestimmt, sonst NULL)
** Skating Regel 11 (optional) [regel11]
*** Array über Endrundenstarter
**** Array über Plätze
***** „Tabellenzelle“ (wenn in Ausrechnung benötigt, sonst NULL)
****** Anzahl [anzahl]
****** Summe (optional, sonst NULL) [summe]
**** Platz (sofern in Regel 11 bestimmt, sonst NULL)

Bei Startern eines anderen Staates, die keine Paar-ID bzw. Partner/in-ID
haben, sind nur die Namen eingetragen, evtl. der Clubname, aber auch der
Staat.

==== Rückgabe

Response-Objekt und HTTP-Ergebnis-Code

=== Ausgefallenes Turnier (schreibend)

Dieser Aufruf ist immer ein Turnierabschluss und startet die
vier-Stunden-Frist zum Schließen des Turniers. Innerhalb der Frist muss
auch ein Upload von „echten“ Ergebnissen ersatzweise möglich sein.

==== Aufruf

* HTTP-Verb: POST
* HTTP Header: User + Passwort (Basic Authentication)
* HTTP Header: User-Agent (Software inkl. Version + Kennschlüssel)
* URL-Parameter: Turnier-ID

[source]
----
POST /api/v1/ausgefallen/{turnierId} HTTP/1.1
Authorization: Basic dXNlcjpwYXNzd29yZA==
User-Agent: Software/1.0; Token=abcdefghijklmnopqrstuvwxyz
----

==== Inhalt

* Vorkommnisse (optional) [vorkommnisse]

==== Rückgabe

Response-Objekt und HTTP-Ergebnis-Code

=== Wertungsrichterzettel PDF (schreibend)

Über diese Schnittstelle können eingescannte Wertungsrichterzettel als
PDF-Dateien hochgeladen werden.

==== Aufruf

* HTTP-Verb: POST
* HTTP Header: User + Passwort (Basic Authentication)
* HTTP Header: User-Agent (Software inkl. Version + Kennschlüssel)
* Content-Type: multipart/form-data
* URL-Parameter: Turnier-ID

[source]
----
POST /api/v1/wrzettelpdf/{turnierId} HTTP/1.1
Authorization: Basic dXNlcjpwYXNzd29yZA==
User-Agent: Software/1.0; Token=abcdefghijklmnopqrstuvwxyz
----

==== Inhalt

Der Multipart-Request-Body enthält beliebig viele PDF-Dateien. Der Name
der Parts kann frei gewählt werden:

[source]
----
Content-Type: multipart/form-data; boundary=----Boundary
----Boundary
Content-Disposition: form-data; name="a"; filename="WRZettel1.pdf"
Content-Type: application/pdf

----Boundary
Content-Disposition: form-data; name="b"; filename="WRZettel2.pdf"
Content-Type: application/pdf
----

==== Rückgabe

Response-Objekt und HTTP-Ergebnis-Code

=== Wertungsrichterzettel digital (schreibend)

Über diese Schnittstelle können die Original-Daten der digitalen
Wertungsrichterzettel hochgeladen werden. Die Verwendung ist nur
zulässig, wenn tatsächlich digitale Wertungsgeräte zum Einsatz kommen.

==== Aufruf

* HTTP-Verb: POST
* HTTP Header: User + Passwort (Basic Authentication)
* HTTP Header: User-Agent (Software inkl. Version + Kennschlüssel)
* URL-Parameter: Turnier-ID
* URL-Parameter: Runde

[source]
----
POST /api/v1/wrzetteldigi/{turnierId}/{runde} HTTP/1.1
Authorization: Basic dXNlcjpwYXNzd29yZA==
User-Agent: Software/1.0; Token=abcdefghijklmnopqrstuvwxyz
----

==== Inhalt

Bei Formations/JMD-Wertungen läuft das Wertungsarray immer über 5/4
virtuelle Tänze +
(Tanz 1-4/3: Wertungsgebiete Punkte 0-10, Tanz 5/4: Kreuz oder Platz).

* URI des verwendeten JSON-Schemas [$schema] (verpflichtend ab
Schnittstellen-Level 2)
* Array über alle WR (in der Reihenfolge wie im Ergebnisupload; das
Element ist NULL, wenn die Wertungen nicht vollständig digital erfasst
wurden, z.B. wenn teilweise oder vollständig auf Papier gewertet wurde)
** Wertungsrichter [wr]
*** Personen-ID [id]
*** Vorname [vorname]
*** Nachname [nachname]
** Kreuzvorgabe von (bei Finale NULL) [kreuzvorgabeVon]
** Kreuzvorgabe bis (bei Finale NULL) [kreuzvorgabeBis]
** Array über Starter [starter]
*** Startnummer [startNr]
*** Array über Tänze (bzw. Wertungsgebiete bei Formation oder JMD)
[wertungen]
**** Wertung (Float oder „L“ für Lift, NULL, falls dieser Tanz in der
Runde nicht getanzt wurde)
*** Float Summe Wertung (NULL bei Platzwertung) [summe]
** Unterschrift (Base64-kodiertes PNG-Bild 1bit, max. 400*200 Pixel)
[unterschrift]

==== Rückgabe

Response-Objekt und HTTP-Ergebnis-Code

== Anhang

=== Schlüsselverzeichnis

==== LTVs

HATV, HTV, LTVBerlin, LTVBr, LTVBremen, LTVB, LTVS, NTV, SLT, TBW, TMV,
TNW, TRP, TSH, TTSV, LTVSA

==== Wettbewerbsarten

Einzel, FormationStdLat, Mannschaft, Solo, SoloMaennlich, SoloWeiblich,
Duo, SmallGroup, FormationJMD

==== Turnierformen

DM (Deutsche Meisterschaft), DP (Deutschlandpokal), DC (Deutschlandcup),
RLT (Rangliste), +
RSRLT (Rising Star Rangliste), GM (Gebietsmeisterschaft), LM
(Landesmeisterschaft), OT (Offenes Turnier), ET (Einladungsturnier), IET
(Int. Einladungsturnier), IM (Int. Meisterschaft), IT (Int. Turnier),
PDT (PD Trophy), LT (Ligaturnier), IMK (Int. Länderkampf Mannschaft), MK
(Mannschaftskampf), +
RM (Regionalmeisterschaft JMD)

==== Startgruppen

KinI, KinII, Kin, JunI, JunII, Jug, Hgr, HgrII, SenI, SenII, SenIII,
SenIV, U21, MCI, MCII

Ggf. Kombinationen aus diesen Abkürzungen (z.B. Jug/Hgr, SenI/II)

==== Startklassen

BSW, D, C, B, A, S, PD, 1BL, 2BL, RL, OL, LL, VL

==== Turnierarten

Std, Lat, Kmb, JMD, SD-Std, SD-Lat

==== Ranglisten-IDs

JunII-Std, JunII-Lat, Jug-Std, Jug-Lat, Hgr-Std, Hgr-Lat, Hgr-RS-Std,
Hgr-RS-Lat, SenI-Std, SenII-Std, G55-Std, LS66-Std, Jug-SoloM-JMD,
Jug-SoloW-JMD, Jug-Duo-JMD, Jug-SG-JMD, Hgr-SoloM-JMD, Hgr-SoloW-JMD,
Hgr-Duo-JMD, Hgr-SG-JMD

==== Lizenztypen

===== Turnierleiter

TL, TL-JMD

===== WR-Einzel

WR-D (alle aktiven C-Tänzer mit WR-C), WR-C, WR-B-Std, WR-B-Lat,
WR-A-Std, WR-A-Lat, WR-S-Std, WR-S-Lat, WR-S-RL-Std, WR-S-RL-Lat,
WR-S-DM-Std, WR-S-DM-Lat

Bemerkung: Bei Angabe von WR-D sollen keine höheren, weiteren
Lizenzwerte übertragen werden.

===== WR-Formation Std/Lat

WR-F1, WR-F2, WR-F-BL, WR-F-DM,

===== WR-JMD

WR-J1, WR-J2, WR-J1-DM, WR-J2-DM

==== Tänze

LW, TG, WW, SF, QU, SB, CC, RB, PD, JV, STD, LAT, JMD, DF, SA (Salsa)

==== Runden

1, R, 2, 3, 4, 5, 6, 7, 8, 9, F +
(Redance=R, bei 1.VR=1A, bei 2.VR=1B, bei Formations A-Finale=FA, bei
B-Finale=FB)

==== Wertungstyp

K (Kreuze), M (Mannschaftspunkte{1..1,5..2..2,5..3}), P
(Finalplätze{1..x}), +
FK (FormationswertungKreuze), FP (FormationswertungPlätze), JK
(JMD-WertungenKreuze), +
JP (JMD-WertungenPlätze), JS (JudgingSystem2.x)

=== Ergebniscodes

* 200 OK
* 403 Login inkorrekt
* 400 Datenkonstrukt ungültig (Bad request)
* 404 Ressource existiert nicht (Ergebnis, Funktionär, Starter etc.)
* 601 Token abgelehnt
* 602 Veranstaltung bereits hochgeladen und Datensatz geschlossen
* 603 Ergebnisupload nach Frist, Turnier wird der nächsten Woche
zugerechnet
* 604 Ergebnisdatensatz unvollständig (Fehlerdetails im response body)
* 605 Starter nicht startberechtigt in angefragter Turnierart
* 606 Datenempfang unvollständig
* 610 Zugriff zur Sandbox abgelehnt, Turnier-ID des Arbeitssystems
verwendet
* Ergebniscodes für Meldeeingänge (z.B. OK, nicht erlaubt, abgelehnt da
Doppelmeldung…)
* Ergebniscodes für Meldebestätigungen (noch offen, bestätigt,
abgelehnt)

=== API-Responses

Schreibzugriffe auf die API liefern ein allgemeines Response-Objekt als
JSON zurück:

* Fehlercode (korrespondiert mit HTTP-Ergebnis-Code) [code]
* Fehlermeldung [fehler]
* Detail (optional) [detail]

