= Schnittstellen Externe Systeme

== Änderungshistorie

*15.04.2015 / Version 1.6*

* Schnittstelle zur gesammelten Abfrage der Clubbestätigungen ergänzt

*12.03.2015 / Version 1.5*

* Schnittstelle zur Prüfung der Starterlaubnis ergänzt
* (Angleichung des Versionsstandes)

*6.12.2014 / Version 1.0*

* Dokumente gesplittet und Interfacereihenfolge überarbeitet

== Schnittstellen

=== Einzelstarterabfrage (lesend)

==== Aufruf

* HTTP-Verb: GET
* HTTP Header: User + Passwort (Basic Authentication)
* HTTP Header: User-Agent (Software inkl. Version + Kennschlüssel)
* URL-Parameter: Starter-ID
* URL-Parameter: Personen-ID/WDSF-MIN, zusammen mit Wettbewerbsart

*Aufruf mit Starter-ID*

[source]
----
GET /api/v1/starter/{starterId} HTTP/1.1
Authorization: Basic dXNlcjpwYXNzd29yZA==
User-Agent: Software/1.0; Token=abcdefghijklmnopqrstuvwxyz
----

*Aufruf mit Personen-ID bzw. WDSF-MIN und Wettbewerbsart*

[source]
----
GET /api/v1/starter/{wettbewerbsart}/{personenId/WDSF-MIN} HTTP/1.1
Authorization: Basic dXNlcjpwYXNzd29yZA==
User-Agent: Software/1.0; Token=abcdefghijklmnopqrstuvwxyz
----

==== Rückgabe

Wie Starter-Eintrag aus Veranstaltungsstartliste (beschrieben in der
Schnittstellen-Dokumentation für Turnierprogramme). Das Feld [meldungen]
ist ein leeres Array.

=== Starterlaubnis abfragen (lesend)

==== Aufruf

* HTTP-Verb: GET
* HTTP Header: User + Passwort (Basic Authentication)
* HTTP Header: User-Agent (Software inkl. Version + Kennschlüssel)
* URL-Parameter: Turnier-ID
* URL-Parameter: Starter-ID

[source]
----
GET /api/v1/starterlaubnis/{turnierId}/{starterId} HTTP/1.1
Authorization: Basic dXNlcjpwYXNzd29yZA==
User-Agent: Software/1.0; Token=abcdefghijklmnopqrstuvwxyz
----

==== Rückgabe

Erlaubnisstatus true oder false (JSON) mit HTTP-Ergebniscode

=== Meldung erfassen (schreibend)

==== Aufruf

* HTTP-Verb: POST
* HTTP Header: User + Passwort (Basic Authentication)
* HTTP Header: User-Agent (Software inkl. Version + Kennschlüssel)
* URL-Parameter: Turnier-ID
* URL-Parameter: Starter-ID
* URL-Parameter: Meldung/Abmeldung als true/false

[source]
----
POST /api/v1/meldung/{turnierId}/{starterId}/{meldungAbmeldung} HTTP/1.1
Authorization: Basic dXNlcjpwYXNzd29yZA==
User-Agent: Software/1.0; Token=abcdefghijklmnopqrstuvwxyz
----

==== Rückgabe

Response-Objekt und HTTP-Ergebnis-Code

=== Bestätigungsstatus (lesend)

==== Aufruf

* HTTP-Verb: GET
* HTTP Header: User + Passwort (Basic Authentication)
* HTTP Header: User-Agent (Software inkl. Version + Kennschlüssel)
* URL-Parameter: Turnier-ID
* URL-Parameter: Starter-ID (optional)

[source]
----
GET /api/v1/bestaetigung/{turnierId}/{starterId} HTTP/1.1
Authorization: Basic dXNlcjpwYXNzd29yZA==
User-Agent: Software/1.0; Token=abcdefghijklmnopqrstuvwxyz
----

==== Rückgabe

* Array Bestätigungsstatus
** StarterId [id]
** Bestätigungsstatus [status] +
true (bestätigt), null (keine Info), false (abgelehnt)

=== Paarergebnisse (lesend)

Aufbereitete Ergebnisse z.B. für Club-CMS

Rückblickend für begrenzten Zeitraum (z.B. vergangenes Wochenende)

==== Aufruf

Datum, Zeitraum, Club

==== Rückgabe

Array aller Ergebnisse der letzten Woche (falls Zeitraum leer)

StarterID, TurnierID, Platz, Punkte
